/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import java.util.Date;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class DateRange  {
  
  @SerializedName("after")
  private Date after = null;
  @SerializedName("before")
  private Date before = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getAfter() {
    return after;
  }
  public void setAfter(Date after) {
    this.after = after;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getBefore() {
    return before;
  }
  public void setBefore(Date before) {
    this.before = before;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DateRange dateRange = (DateRange) o;
    return (after == null ? dateRange.after == null : after.equals(dateRange.after)) &&
        (before == null ? dateRange.before == null : before.equals(dateRange.before));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (after == null ? 0: after.hashCode());
    result = 31 * result + (before == null ? 0: before.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DateRange {\n");
    
    sb.append("  after: ").append(after).append("\n");
    sb.append("  before: ").append(before).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
