/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.DateRange;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class InlineResponse20041  {
  
  @SerializedName("daterange")
  private DateRange daterange = null;
  @SerializedName("source_frequency")
  private List<Integer> sourceFrequency = null;
  @SerializedName("source_revenue")
  private List<Integer> sourceRevenue = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public DateRange getDaterange() {
    return daterange;
  }
  public void setDaterange(DateRange daterange) {
    this.daterange = daterange;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Integer> getSourceFrequency() {
    return sourceFrequency;
  }
  public void setSourceFrequency(List<Integer> sourceFrequency) {
    this.sourceFrequency = sourceFrequency;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Integer> getSourceRevenue() {
    return sourceRevenue;
  }
  public void setSourceRevenue(List<Integer> sourceRevenue) {
    this.sourceRevenue = sourceRevenue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20041 inlineResponse20041 = (InlineResponse20041) o;
    return (daterange == null ? inlineResponse20041.daterange == null : daterange.equals(inlineResponse20041.daterange)) &&
        (sourceFrequency == null ? inlineResponse20041.sourceFrequency == null : sourceFrequency.equals(inlineResponse20041.sourceFrequency)) &&
        (sourceRevenue == null ? inlineResponse20041.sourceRevenue == null : sourceRevenue.equals(inlineResponse20041.sourceRevenue));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (daterange == null ? 0: daterange.hashCode());
    result = 31 * result + (sourceFrequency == null ? 0: sourceFrequency.hashCode());
    result = 31 * result + (sourceRevenue == null ? 0: sourceRevenue.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20041 {\n");
    
    sb.append("  daterange: ").append(daterange).append("\n");
    sb.append("  sourceFrequency: ").append(sourceFrequency).append("\n");
    sb.append("  sourceRevenue: ").append(sourceRevenue).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
