/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.Addon;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class InlineResponse20010  {
  
  @SerializedName("status")
  private String status = null;
  @SerializedName("id")
  private Long id = null;
  @SerializedName("addons")
  private List<Addon> addons = null;
  @SerializedName("decimal_price")
  private String decimalPrice = null;
  @SerializedName("boatroom_id")
  private Long boatroomId = null;
  @SerializedName("package_decimal_price")
  private String packageDecimalPrice = null;
  @SerializedName("course_decimal_price")
  private String courseDecimalPrice = null;
  @SerializedName("ticket_decimal_price")
  private String ticketDecimalPrice = null;
  @SerializedName("packagefacade_id")
  private String packagefacadeId = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Addon> getAddons() {
    return addons;
  }
  public void setAddons(List<Addon> addons) {
    this.addons = addons;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDecimalPrice() {
    return decimalPrice;
  }
  public void setDecimalPrice(String decimalPrice) {
    this.decimalPrice = decimalPrice;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getBoatroomId() {
    return boatroomId;
  }
  public void setBoatroomId(Long boatroomId) {
    this.boatroomId = boatroomId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPackageDecimalPrice() {
    return packageDecimalPrice;
  }
  public void setPackageDecimalPrice(String packageDecimalPrice) {
    this.packageDecimalPrice = packageDecimalPrice;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCourseDecimalPrice() {
    return courseDecimalPrice;
  }
  public void setCourseDecimalPrice(String courseDecimalPrice) {
    this.courseDecimalPrice = courseDecimalPrice;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTicketDecimalPrice() {
    return ticketDecimalPrice;
  }
  public void setTicketDecimalPrice(String ticketDecimalPrice) {
    this.ticketDecimalPrice = ticketDecimalPrice;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPackagefacadeId() {
    return packagefacadeId;
  }
  public void setPackagefacadeId(String packagefacadeId) {
    this.packagefacadeId = packagefacadeId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20010 inlineResponse20010 = (InlineResponse20010) o;
    return (status == null ? inlineResponse20010.status == null : status.equals(inlineResponse20010.status)) &&
        (id == null ? inlineResponse20010.id == null : id.equals(inlineResponse20010.id)) &&
        (addons == null ? inlineResponse20010.addons == null : addons.equals(inlineResponse20010.addons)) &&
        (decimalPrice == null ? inlineResponse20010.decimalPrice == null : decimalPrice.equals(inlineResponse20010.decimalPrice)) &&
        (boatroomId == null ? inlineResponse20010.boatroomId == null : boatroomId.equals(inlineResponse20010.boatroomId)) &&
        (packageDecimalPrice == null ? inlineResponse20010.packageDecimalPrice == null : packageDecimalPrice.equals(inlineResponse20010.packageDecimalPrice)) &&
        (courseDecimalPrice == null ? inlineResponse20010.courseDecimalPrice == null : courseDecimalPrice.equals(inlineResponse20010.courseDecimalPrice)) &&
        (ticketDecimalPrice == null ? inlineResponse20010.ticketDecimalPrice == null : ticketDecimalPrice.equals(inlineResponse20010.ticketDecimalPrice)) &&
        (packagefacadeId == null ? inlineResponse20010.packagefacadeId == null : packagefacadeId.equals(inlineResponse20010.packagefacadeId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (status == null ? 0: status.hashCode());
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (addons == null ? 0: addons.hashCode());
    result = 31 * result + (decimalPrice == null ? 0: decimalPrice.hashCode());
    result = 31 * result + (boatroomId == null ? 0: boatroomId.hashCode());
    result = 31 * result + (packageDecimalPrice == null ? 0: packageDecimalPrice.hashCode());
    result = 31 * result + (courseDecimalPrice == null ? 0: courseDecimalPrice.hashCode());
    result = 31 * result + (ticketDecimalPrice == null ? 0: ticketDecimalPrice.hashCode());
    result = 31 * result + (packagefacadeId == null ? 0: packagefacadeId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20010 {\n");
    
    sb.append("  status: ").append(status).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  addons: ").append(addons).append("\n");
    sb.append("  decimalPrice: ").append(decimalPrice).append("\n");
    sb.append("  boatroomId: ").append(boatroomId).append("\n");
    sb.append("  packageDecimalPrice: ").append(packageDecimalPrice).append("\n");
    sb.append("  courseDecimalPrice: ").append(courseDecimalPrice).append("\n");
    sb.append("  ticketDecimalPrice: ").append(ticketDecimalPrice).append("\n");
    sb.append("  packagefacadeId: ").append(packagefacadeId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
