/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;


import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class Schedule  {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("weeks")
  private String weeks = null;
  @SerializedName("schedule")
  private String schedule = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getWeeks() {
    return weeks;
  }
  public void setWeeks(String weeks) {
    this.weeks = weeks;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSchedule() {
    return schedule;
  }
  public void setSchedule(String schedule) {
    this.schedule = schedule;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Schedule schedule = (Schedule) o;
    return (id == null ? schedule.id == null : id.equals(schedule.id)) &&
        (weeks == null ? schedule.weeks == null : weeks.equals(schedule.weeks)) &&
        (schedule == null ? schedule.schedule == null : schedule.equals(schedule.schedule));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (weeks == null ? 0: weeks.hashCode());
    result = 31 * result + (schedule == null ? 0: schedule.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Schedule {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  weeks: ").append(weeks).append("\n");
    sb.append("  schedule: ").append(schedule).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
