/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.Trip;
import java.util.*;
import java.util.Date;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class Ticket  {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("only_packaged")
  private Boolean onlyPackaged = null;
  @SerializedName("available_from")
  private Date availableFrom = null;
  @SerializedName("available_until")
  private Date availableUntil = null;
  @SerializedName("trips")
  private List<Trip> trips = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getOnlyPackaged() {
    return onlyPackaged;
  }
  public void setOnlyPackaged(Boolean onlyPackaged) {
    this.onlyPackaged = onlyPackaged;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getAvailableFrom() {
    return availableFrom;
  }
  public void setAvailableFrom(Date availableFrom) {
    this.availableFrom = availableFrom;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getAvailableUntil() {
    return availableUntil;
  }
  public void setAvailableUntil(Date availableUntil) {
    this.availableUntil = availableUntil;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Trip> getTrips() {
    return trips;
  }
  public void setTrips(List<Trip> trips) {
    this.trips = trips;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Ticket ticket = (Ticket) o;
    return (id == null ? ticket.id == null : id.equals(ticket.id)) &&
        (name == null ? ticket.name == null : name.equals(ticket.name)) &&
        (description == null ? ticket.description == null : description.equals(ticket.description)) &&
        (onlyPackaged == null ? ticket.onlyPackaged == null : onlyPackaged.equals(ticket.onlyPackaged)) &&
        (availableFrom == null ? ticket.availableFrom == null : availableFrom.equals(ticket.availableFrom)) &&
        (availableUntil == null ? ticket.availableUntil == null : availableUntil.equals(ticket.availableUntil)) &&
        (trips == null ? ticket.trips == null : trips.equals(ticket.trips));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (name == null ? 0: name.hashCode());
    result = 31 * result + (description == null ? 0: description.hashCode());
    result = 31 * result + (onlyPackaged == null ? 0: onlyPackaged.hashCode());
    result = 31 * result + (availableFrom == null ? 0: availableFrom.hashCode());
    result = 31 * result + (availableUntil == null ? 0: availableUntil.hashCode());
    result = 31 * result + (trips == null ? 0: trips.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Ticket {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  onlyPackaged: ").append(onlyPackaged).append("\n");
    sb.append("  availableFrom: ").append(availableFrom).append("\n");
    sb.append("  availableUntil: ").append(availableUntil).append("\n");
    sb.append("  trips: ").append(trips).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
