/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.Training;
import java.util.Date;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class TrainingSession  {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("start")
  private Date start = null;
  @SerializedName("schedule_id")
  private Long scheduleId = null;
  @SerializedName("capacity")
  private Integer capacity = null;
  @SerializedName("class")
  private Training _class = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getStart() {
    return start;
  }
  public void setStart(Date start) {
    this.start = start;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getScheduleId() {
    return scheduleId;
  }
  public void setScheduleId(Long scheduleId) {
    this.scheduleId = scheduleId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getCapacity() {
    return capacity;
  }
  public void setCapacity(Integer capacity) {
    this.capacity = capacity;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Training getClass() {
    return _class;
  }
  public void setClass(Training _class) {
    this._class = _class;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainingSession trainingSession = (TrainingSession) o;
    return (id == null ? trainingSession.id == null : id.equals(trainingSession.id)) &&
        (start == null ? trainingSession.start == null : start.equals(trainingSession.start)) &&
        (scheduleId == null ? trainingSession.scheduleId == null : scheduleId.equals(trainingSession.scheduleId)) &&
        (capacity == null ? trainingSession.capacity == null : capacity.equals(trainingSession.capacity)) &&
        (_class == null ? trainingSession._class == null : _class.equals(trainingSession._class));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (start == null ? 0: start.hashCode());
    result = 31 * result + (scheduleId == null ? 0: scheduleId.hashCode());
    result = 31 * result + (capacity == null ? 0: capacity.hashCode());
    result = 31 * result + (_class == null ? 0: _class.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainingSession {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  start: ").append(start).append("\n");
    sb.append("  scheduleId: ").append(scheduleId).append("\n");
    sb.append("  capacity: ").append(capacity).append("\n");
    sb.append("  _class: ").append(_class).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
