/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.model;

import io.swagger.client.model.Customer;
import io.swagger.client.model.TrainingSessionManifestCapacity;
import java.util.*;
import java.util.Date;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


@ApiModel(description = "")
public class TrainingSessionManifest  {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("training_id")
  private Long trainingId = null;
  @SerializedName("start")
  private Date start = null;
  @SerializedName("schedule_id")
  private Long scheduleId = null;
  @SerializedName("customers")
  private List<Customer> customers = null;
  @SerializedName("capacity")
  private TrainingSessionManifestCapacity capacity = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getTrainingId() {
    return trainingId;
  }
  public void setTrainingId(Long trainingId) {
    this.trainingId = trainingId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getStart() {
    return start;
  }
  public void setStart(Date start) {
    this.start = start;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getScheduleId() {
    return scheduleId;
  }
  public void setScheduleId(Long scheduleId) {
    this.scheduleId = scheduleId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Customer> getCustomers() {
    return customers;
  }
  public void setCustomers(List<Customer> customers) {
    this.customers = customers;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public TrainingSessionManifestCapacity getCapacity() {
    return capacity;
  }
  public void setCapacity(TrainingSessionManifestCapacity capacity) {
    this.capacity = capacity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrainingSessionManifest trainingSessionManifest = (TrainingSessionManifest) o;
    return (id == null ? trainingSessionManifest.id == null : id.equals(trainingSessionManifest.id)) &&
        (trainingId == null ? trainingSessionManifest.trainingId == null : trainingId.equals(trainingSessionManifest.trainingId)) &&
        (start == null ? trainingSessionManifest.start == null : start.equals(trainingSessionManifest.start)) &&
        (scheduleId == null ? trainingSessionManifest.scheduleId == null : scheduleId.equals(trainingSessionManifest.scheduleId)) &&
        (customers == null ? trainingSessionManifest.customers == null : customers.equals(trainingSessionManifest.customers)) &&
        (capacity == null ? trainingSessionManifest.capacity == null : capacity.equals(trainingSessionManifest.capacity));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (id == null ? 0: id.hashCode());
    result = 31 * result + (trainingId == null ? 0: trainingId.hashCode());
    result = 31 * result + (start == null ? 0: start.hashCode());
    result = 31 * result + (scheduleId == null ? 0: scheduleId.hashCode());
    result = 31 * result + (customers == null ? 0: customers.hashCode());
    result = 31 * result + (capacity == null ? 0: capacity.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrainingSessionManifest {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  trainingId: ").append(trainingId).append("\n");
    sb.append("  start: ").append(start).append("\n");
    sb.append("  scheduleId: ").append(scheduleId).append("\n");
    sb.append("  customers: ").append(customers).append("\n");
    sb.append("  capacity: ").append(capacity).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
